name: protein_analysis_md
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pydantic
  - typer
  - pyyaml
  - requests
  - mdtraj
  - mdanalysis
  - openmm
  - pyarrow
  - pytest
  - ruff
  - pip
  - pip:
      - git+https://github.com/KULL-Centre/CALVADOS.git
