"""Variant design and Stage 2 design-output generation."""

from __future__ import annotations

import csv
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import yaml

from idrptm.ptm import AppliedPTM, PTMRequest, PTMState, apply_ptms
from idrptm.schema import PTMSite, WorkflowConfig, load_config
from idrptm.sequence import (
    SequenceRecord,
    load_single_sequence,
    sanitize_identifier,
    write_fasta,
)


@dataclass(frozen=True)
class DesignedVariant:
    """A sequence/PTM design ready to be translated into backend input."""

    variant_id: str
    base_sequence: SequenceRecord
    original_sequence: str
    simulation_sequence: str
    ptm_state: PTMState

    @property
    def is_wild_type(self) -> bool:
        """Return true for the unmodified original-sequence design."""

        return self.ptm_state.is_wild_type


@dataclass(frozen=True)
class DesignOutput:
    """Paths generated by the design command."""

    output_dir: Path
    manifest_path: Path
    fasta_paths: tuple[Path, ...]
    metadata_paths: tuple[Path, ...]
    variants: tuple[DesignedVariant, ...]


def _request_from_site(site: PTMSite) -> PTMRequest:
    return PTMRequest(
        biological_position=site.position,
        ptm=site.ptm,
        expected_residue=site.residue,
    )


def _discover_phosphorylation_sites(sequence: SequenceRecord) -> tuple[PTMRequest, ...]:
    requests: list[PTMRequest] = []
    for zero_based_index, residue in enumerate(sequence.sequence):
        if residue == "S":
            requests.append(
                PTMRequest(
                    biological_position=zero_based_index + 1,
                    ptm="pSer",
                    expected_residue="S",
                )
            )
        elif residue == "T":
            requests.append(
                PTMRequest(
                    biological_position=zero_based_index + 1,
                    ptm="pThr",
                    expected_residue="T",
                )
            )
    return tuple(requests)


def _site_label(applied_sites: Iterable[AppliedPTM]) -> str:
    labels = [
        f"{site.ptm}{site.biological_position}"
        for site in sorted(applied_sites, key=lambda item: item.zero_based_index)
    ]
    return "_".join(labels) if labels else "WT"


def _variant_id(sequence_name: str, applied_sites: tuple[AppliedPTM, ...]) -> str:
    return sanitize_identifier(f"{sequence_name}__{_site_label(applied_sites)}")


def _configured_requests(
    config: WorkflowConfig,
    sequence: SequenceRecord,
) -> list[tuple[PTMRequest, ...]]:
    configured_sites = tuple(_request_from_site(site) for site in config.ptm.sites)
    discovered_sites = _discover_phosphorylation_sites(sequence)

    if config.ptm.mode == "wt":
        return []
    if config.ptm.mode == "explicit":
        return [configured_sites]
    if config.ptm.mode == "single_site_scan":
        sites = configured_sites or discovered_sites
        return [(site,) for site in sites]
    if config.ptm.mode == "all_sites":
        sites = configured_sites or discovered_sites
        return [sites] if sites else []
    raise ValueError(f"Unsupported PTM mode: {config.ptm.mode}")


def load_configured_sequence(config: WorkflowConfig) -> SequenceRecord:
    """Load the sequence configured for a workflow."""

    return load_single_sequence(
        name=config.sequence.name,
        sequence=config.sequence.sequence,
        fasta=config.sequence.fasta,
    )


def design_variants(config: WorkflowConfig) -> tuple[DesignedVariant, ...]:
    """Design WT/PTM variants from a workflow config."""

    sequence = load_configured_sequence(config)
    variants: list[DesignedVariant] = []

    if config.ptm.include_wt or config.ptm.mode == "wt":
        wt_state = PTMState(name="WT")
        variants.append(
            DesignedVariant(
                variant_id=_variant_id(sequence.name, ()),
                base_sequence=sequence,
                original_sequence=sequence.sequence,
                simulation_sequence=sequence.sequence,
                ptm_state=wt_state,
            )
        )

    seen_variant_ids = {variant.variant_id for variant in variants}
    for requests in _configured_requests(config, sequence):
        simulation_sequence, applied_sites = apply_ptms(sequence.sequence, requests)
        variant_id = _variant_id(sequence.name, applied_sites)
        if variant_id in seen_variant_ids:
            continue
        seen_variant_ids.add(variant_id)
        variants.append(
            DesignedVariant(
                variant_id=variant_id,
                base_sequence=sequence,
                original_sequence=sequence.sequence,
                simulation_sequence=simulation_sequence,
                ptm_state=PTMState(name=_site_label(applied_sites), sites=applied_sites),
            )
        )

    return tuple(sorted(variants, key=_variant_sort_key))


def _variant_sort_key(variant: DesignedVariant) -> tuple[int, tuple[int, ...], str]:
    if variant.is_wild_type:
        return (0, (), variant.variant_id)
    positions = tuple(site.zero_based_index for site in variant.ptm_state.sites)
    return (1, positions, variant.variant_id)


def _site_summary_1based(variant: DesignedVariant) -> str:
    return ";".join(
        f"{site.ptm}:{site.source_residue}{site.biological_position}->{site.simulation_code}"
        for site in variant.ptm_state.sites
    )


def _site_summary_0based(variant: DesignedVariant) -> str:
    return ";".join(
        f"{site.ptm}:{site.zero_based_index}:{site.source_residue}->{site.simulation_code}"
        for site in variant.ptm_state.sites
    )


def _metadata_dict(config: WorkflowConfig, variant: DesignedVariant) -> dict[str, object]:
    return {
        "schema_version": 1,
        "project": config.project,
        "variant_id": variant.variant_id,
        "base_sequence_name": variant.base_sequence.name,
        "original_sequence": variant.original_sequence,
        "simulation_sequence": variant.simulation_sequence,
        "ptms": [
            {
                "ptm": site.ptm,
                "biological_position": site.biological_position,
                "zero_based_index": site.zero_based_index,
                "source_residue": site.source_residue,
                "simulation_code": site.simulation_code,
            }
            for site in variant.ptm_state.sites
        ],
        "calvados": {
            "model": config.calvados.model,
            "temperature_k": config.calvados.temperature_k,
            "ph": config.calvados.ph,
        },
        "status": {
            "calvados_inputs": "not_prepared",
            "simulation": "not_started",
            "analysis": "not_started",
        },
    }


def write_design_outputs(
    config: WorkflowConfig,
    output_dir: str | Path | None = None,
) -> DesignOutput:
    """Write manifest, variant FASTA files, and metadata stubs."""

    root = Path(output_dir) if output_dir is not None else config.runner.work_dir
    root.mkdir(parents=True, exist_ok=True)
    fasta_dir = root / "fasta"
    runs_dir = root / "runs"
    fasta_dir.mkdir(parents=True, exist_ok=True)
    runs_dir.mkdir(parents=True, exist_ok=True)

    variants = design_variants(config)
    manifest_path = root / "manifest.csv"
    fasta_paths: list[Path] = []
    metadata_paths: list[Path] = []

    rows: list[dict[str, object]] = []
    for variant in variants:
        fasta_path = fasta_dir / f"{variant.variant_id}.fasta"
        metadata_path = runs_dir / variant.variant_id / "metadata.yaml"
        metadata_path.parent.mkdir(parents=True, exist_ok=True)

        fasta_record = SequenceRecord(
            name=variant.variant_id,
            sequence=variant.original_sequence,
            description=f"simulation_sequence for {config.project}",
        )
        write_fasta(fasta_record, fasta_path, sequence=variant.simulation_sequence)
        metadata_path.write_text(
            yaml.safe_dump(_metadata_dict(config, variant), sort_keys=False),
            encoding="utf-8",
        )

        fasta_relative = fasta_path.relative_to(root).as_posix()
        metadata_relative = metadata_path.relative_to(root).as_posix()
        rows.append(
            {
                "project": config.project,
                "variant_id": variant.variant_id,
                "base_sequence_name": variant.base_sequence.name,
                "ptm_state": variant.ptm_state.name,
                "ptm_count": len(variant.ptm_state.sites),
                "ptm_sites_1based": _site_summary_1based(variant),
                "ptm_sites_0based": _site_summary_0based(variant),
                "original_sequence": variant.original_sequence,
                "simulation_sequence": variant.simulation_sequence,
                "fasta_path": fasta_relative,
                "metadata_path": metadata_relative,
            }
        )
        fasta_paths.append(fasta_path)
        metadata_paths.append(metadata_path)

    fieldnames = [
        "project",
        "variant_id",
        "base_sequence_name",
        "ptm_state",
        "ptm_count",
        "ptm_sites_1based",
        "ptm_sites_0based",
        "original_sequence",
        "simulation_sequence",
        "fasta_path",
        "metadata_path",
    ]
    with manifest_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    return DesignOutput(
        output_dir=root,
        manifest_path=manifest_path,
        fasta_paths=tuple(fasta_paths),
        metadata_paths=tuple(metadata_paths),
        variants=variants,
    )


def design_from_config_file(
    config_path: str | Path,
    output_dir: str | Path | None = None,
) -> DesignOutput:
    """Load a workflow config and write Stage 2 design outputs."""

    return write_design_outputs(load_config(config_path), output_dir=output_dir)
